name: Tests

on:
  push:
    branches: [ "master" ]

jobs:
  unit_integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Installer dépendances CI (pip)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-ci.txt

      - name: Run unit tests
        env:
          PYTHONPATH: ${{ github.workspace }}/src
        run: |
          python -m pytest -q tests/unit -k "not deep_learning and not prediction"

      - name: Run integration tests
        env:
          PYTHONPATH: ${{ github.workspace }}/src
        run: |
          python -m pytest -q tests/integration -k "not deep_learning and not prediction"

  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Installer dépendances CI (pip)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-ci.txt

      - name: Run E2E tests
        env:
          PYTHONPATH: ${{ github.workspace }}/src
        run: |
          python -m pytest -q tests/e2e -k "not deep_learning and not prediction"